/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.kentrino.thedependency

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class TheDependencyTest {
    @Test
    fun `test version string is correct`() {
        assertEquals("0.0.3", TheDependency.version)
    }
}
